name: 'Publish @cemento/axios-digest-fork'

on:
  push:
    branches:
      - master   # Trigger on every push to master

env:
  PROJECT_ID: 'planme-1383'
  PACKAGE_DIR: '.'   # Path to your package containing package.json

permissions:
  contents: 'read'
  id-token: 'write'  # Needed for Workload Identity authentication

jobs:
  publish:
    name: 'Publish axios-digest-fork to @cemento'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.PACKAGE_DIR }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          workload_identity_provider: projects/232804422965/locations/global/workloadIdentityPools/github-actions-bot/providers/oidc-provider
          service_account: github-actions@planme-1383.iam.gserviceaccount.com

      - name: Configure npm registry
        run: |
          echo "@cemento:registry=https://us-central1-npm.pkg.dev/${{ env.PROJECT_ID }}/cemento/" > .npmrc
          echo "always-auth=true" >> .npmrc

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build --if-present

      - name: Publish @cemento/axios-digest-fork
        run: npm publish --registry=https://us-central1-npm.pkg.dev/${{ env.PROJECT_ID }}/cemento/
