name: 'Publish axios-digest-fork'

on:
  push:
    branches:
      - master   # triggers on merge to master

env:
  PROJECT_ID: 'planme-1383'
  PACKAGE_DIR: '.'

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Authenticate with Google
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          workload_identity_provider: 'projects/232804422965/locations/global/workloadIdentityPools/github-actions-bot/providers/oidc-provider'
          service_account: 'github-actions@planme-1383.iam.gserviceaccount.com'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Create .npmrc
        run: echo "@cemento:registry=https://us-central1-npm.pkg.dev/${{ env.PROJECT_ID }}/cemento/" >> .npmrc

      - name: Install dependencies
        run: npm install

      - name: Build package
        run: npm run build

      - name: Publish package to GCP
        run: npm run artifactregistry-login && npm publish --registry=https://us-central1-npm.pkg.dev/planme-1383/cemento/
